version: '3.8'

services:
  web:
    build: .
    image: site-saudeflow:latest
    ports:
      - "20080:80"
    restart: unless-stopped

  # Adicione no docker-compose.yml
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
