
services:
  web:
    image: nginx:alpine
    container_name: empresa-site
    restart: unless-stopped
    ports:
      - "20008:80"
    volumes:
      - ./site:/usr/share/nginx/html  # Diretório modificado
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
