version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: saudeflow-site
    restart: unless-stopped
    ports:
      - "20008:80"
    volumes:
      - ./seu-site:/usr/share/nginx/html
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
