services:
  web:
    image: nginx:alpine
    ports:
      - "20009:80"
    volumes:
      - /data/compose/27/site:/usr/share/nginx/html:ro
    deploy:
      restart_policy:
        condition: any
    networks:
      - app_network

networks:
  app_network:
    driver: overlay
