version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: saudeflow-site
    restart: unless-stopped
    ports:
      - "20009:80"
    volumes:
      - ./site:/usr/share/nginx/html
    networks:
      - site_network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  site_network:
    driver: bridge
