version: "3.8"

services:
  static-site:
    image: busybox:latest
    command: /bin/httpd -f -p 8080 -h /www
    volumes:
      - ./site:/www:ro
    restart: always
    ports:
      - "20009:8080"

networks:
  app_network:
    driver: overlay
