version: '3.8'

services:
  web:
    image: danielcarvalho/site-saudeflow:latest  # Pré-buildar a imagem
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "20080:80"
